name: mobile_core_kit_lints
description: Custom lint rules for the mobile-core-kit template.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.9.2

dependencies:
  analyzer: ^8.0.0
  custom_lint_builder: ^0.8.1
  glob: ^2.1.3
  path: ^1.9.1
  yaml: ^3.1.3

